# -*- coding: utf-8 -*-
"""Assigment1_Srishti2023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cMHr3DUVCFzrko3sUYTXrNhl5941ecPU
"""

#Extend Method

#List
ls = [1,2,3]
ls1 = [4,5,6]
print("Extending the list : ")
ls.extend(ls1)
print("Appending the list with 3 : ")
ls.append(3)
ls.sort()
print("Sorting the list given :")


print(ls)


#tuple
print("Tuple")
t = (1,2,3)
t1 = (4,5,6,2)
t3 = t1+t
print("Count of 2 value in the tuple : ",t3.count(2))
print("Index of 4 value in the tuple :",t3.index(4))


#set method
print("Set Operations")
s = {1,2,34,56}
print(s)
s.add(99)
print("After adding :",s)
s.remove(34)
print("Removig a element :",s)
print("Updating the one set with another \"s with s1\"")
s1 = {399,573,273}
s.update(s1)
print("After updating the set (s) : ",s)


#dictionary

di = {1:"H",2:"E",3:"L"}
print("Items in the Dictionary : ")
print(di.items())
print("Keys in the Dictionary")
print(di.keys())
di.clear()
print("Clearing the elements in the dictionary : ")
print(di)

#Function to add Reverse the first and second as it is
#Question 1
def F_R(a,b):
  return a[::-1]+b

F_R("Hello","Bye")

#Question 2
def Sal(work_hours):
  a = 0
  for x in work_hours:
    if x[-1] == 'F':
      if(a < x[-2]):
        a = x[-2]
        nam = x[-3] 
  return nam,a*20

work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]


name,sal=Sal(work_hours)
print("the female worker that worked the most hours is",name,"and she should be paid",sal)

#Question2_2

import numpy as np

arr = [[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]]
arr = np.vstack(arr)
print(arr)
print()
id = np.eye(5)
print(id)
print()
print(arr@id)
print()
print(arr.shape)
print()
print(np.size(arr))

#Question3
!pip install matplotlib

from google.colab import drive

drive.mount('/content/drive')

from PIL import Image

image_path = '/content/drive/MyDrive/Images/assigment_1_img.jpeg'
image = Image.open(image_path)

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

file_name = "assigment_1_img.jpeg"  


image = mpimg.imread(file_name)


plt.imshow(image)
plt.axis('off')
plt.show()

